name: Update File Count

on:
  push:
    branches:
      - main  

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count files
        id: file_count
        run: |
          shopt -s extglob  # Enable extended globbing
          file_count=$(ls -1 !(README.md|update-file.txt) | wc -l)
          echo "::set-output name=count::$file_count"

      - name: Update README.md
        run: |
          sed -i 's/{{ FILE_COUNT }}/${{ steps.file_count.outputs.count }}/' README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: update file count in README.md" --no-verify

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
