name: Update README

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count files by language
        id: count
        run: |
          echo "Language: ${{ env.LANGUAGE }}"
          count=$(find . -name "*.${{ env.LANGUAGE }}" | wc -l)
          echo "::set-output name=count::$count"

      - name: Update README
        run: |
          sed -i 's/{{ FILE_COUNT }}/$(echo ${{ steps.count.outputs.count }})/' README.md
